#!/bin/sh

#vars

#check for active connections on this ports, list space separated
PORTS="80 443 22"
#run following command if no sessions found
COMMAND="echo -n mem > /sys/power/state"

can_shutdown=1

#check the port list
for port in $PORTS; do
        netstat -an | grep ESTABLISHED | awk '{print $4}' | grep -q "\:$port\$"

        if [[ $? -eq 0 ]]; then
                can_shutdown=0
                break
        fi
        
done

#shutdown if allowed
if [[ $can_shutdown -eq 1 ]]; then
        $COMMAND
fi
